---
- name: (completion) create completion dir
  ansible.builtin.file:
    path: "{{ takel_hugo_completion_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

# https://gohugo.io/commands/hugo_completion/
- name: (completion) add hugo autocompletion
  ansible.builtin.shell: >-
    hugo completion bash > {{ takel_hugo_bash_completion }}
  args:
    creates: "{{ takel_hugo_bash_completion }}"
