---
- name: (main) include version
  import_tasks: version.yml
  when: takel_hugo_hugo_version == 'latest'
  tags:
    - takel
    - takel_hugo
    - takel_hugo_version

- name: (main) include install
  import_tasks: install.yml
  tags:
    - takel
    - takel_hugo
    - takel_hugo_install

- name: (main) include completion
  import_tasks: completion.yml
  tags:
    - takel
    - takel_hugo
    - takel_hugo_completion
