---
- name: (version) install python3-pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: true

- name: (version) install github3.py
  ansible.builtin.pip:
    name: github3.py

- name: (version) get latest release of hugo
  community.general.github_release:
    user: gohugoio
    repo: hugo
    action: latest_release
  register: takel_hugo_latest_version

- name: (version) extract version
  ansible.builtin.set_fact:
    takel_hugo_hugo_version: >-
      {{ takel_hugo_latest_version.tag | split('v') | last }}
