---
- name: (version) get hugo version
  ansible.builtin.shell:
    cmd: curl -s https://github.com/gohugoio/hugo/releases | grep 'gohugoio/hugo/releases/tag/' | head -1 | sed -E 's#.*">v(.*)</a>.*#\1#'  # yamllint disable-line rule:line-length
  register: takel_hugo_hugo_latest_version
  delegate_to: localhost
  changed_when: false

- name: (version) set hugo version
  ansible.builtin.set_fact:
    takel_hugo_hugo_version: >-
      {{ takel_hugo_hugo_latest_version.stdout }}
